name: "push-to-cdn"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "public/sporing/**"

jobs:
  upload:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v4"

      - id: upload
        uses: navikt/frontend/actions/cdn-upload/v2@main
        with:
          cdn-team-name: team-researchops
          source: ./public/sporing
          destination: "/sporing" # uploads folder to team root

      - run: echo uploaded file ${{ steps.upload.outputs.uploaded }}
        shell: bash