name: "push-to-cdn"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "public/sporing/**"

jobs:
  upload:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v4"

      - name: Upload static files to CDN
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: team-researchops
          source: ./public/sporing
          destination: "" # uploads folder to team root
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - run: echo uploaded file ${{ steps.upload.outputs.uploaded }}
        shell: bash